@startuml
activate startup
activate initializePartitionState
startup-> initializePartitionState:
initializePartitionState--> startup:
deactivate initializePartitionState

activate triggerOnlinePartitionStateChange
startup-> triggerOnlinePartitionStateChange
triggerOnlinePartitionStateChange-> handleStateChanges 

activate handleStateChanges
handleStateChanges-> controllerChannelManager: 调用newBatch方法
controllerChannelManager--> handleStateChanges:无返回值

activate doHandleStateChanges
handleStateChanges-> doHandleStateChanges

opt uninitializedPartitions.nonEmpty
activate initializeLeaderAndIsrForPartitions
doHandleStateChanges-> initializeLeaderAndIsrForPartitions
activate controllerChannelManager
initializeLeaderAndIsrForPartitions-> controllerChannelManager: 调用addLeaderAndIsrRequestForBrokers方法
controllerChannelManager--> initializeLeaderAndIsrForPartitions: 无返回值
deactivate controllerChannelManager
initializeLeaderAndIsrForPartitions--> doHandleStateChanges
deactivate initializeLeaderAndIsrForPartitions
end
deactivate doHandleStateChanges

opt partitionsToElectLeader.nonEmpty
activate doHandleStateChanges
activate electLeaderForPartitions
doHandleStateChanges-> electLeaderForPartitions
electLeaderForPartitions-> doElectLeaderForPartitions

opt partitionLeaderElectionStrategy match OfflinePartitionLeaderElectionStrategy
doElectLeaderForPartitions-> leaderForOffline
activate doElectLeaderForPartitions
activate leaderForOffline
deactivate doElectLeaderForPartitions
deactivate leaderForOffline
leaderForOffline--> doElectLeaderForPartitions
end
opt partitionLeaderElectionStrategy match ReassignPartitionLeaderElectionStrategy
doElectLeaderForPartitions-> leaderForReassign
activate doElectLeaderForPartitions
activate leaderForReassign
deactivate doElectLeaderForPartitions
deactivate leaderForReassign
leaderForReassign--> doElectLeaderForPartitions
end
opt partitionLeaderElectionStrategy match PreferredReplicaPartitionLeaderElectionStrategy
doElectLeaderForPartitions-> leaderForPreferredReplica 
activate doElectLeaderForPartitions
activate leaderForPreferredReplica 
deactivate doElectLeaderForPartitions
deactivate leaderForPreferredReplica 
leaderForPreferredReplica--> doElectLeaderForPartitions
end
opt partitionLeaderElectionStrategy match ControlledShutdownPartitionLeaderElectionStrategy
doElectLeaderForPartitions-> leaderForControlledShutdown
activate doElectLeaderForPartitions
activate leaderForControlledShutdown
deactivate doElectLeaderForPartitions
deactivate leaderForControlledShutdown
leaderForControlledShutdown--> doElectLeaderForPartitions 
end

doElectLeaderForPartitions--> electLeaderForPartitions 
electLeaderForPartitions--> doHandleStateChanges
deactivate electLeaderForPartitions
end

doHandleStateChanges--> handleStateChanges
deactivate doHandleStateChanges

handleStateChanges-> controllerChannelManager: 调用sendRequestsToBrokers方法
controllerChannelManager--> handleStateChanges:无返回值
deactivate handleStateChanges

handleStateChanges--> triggerOnlinePartitionStateChange 
triggerOnlinePartitionStateChange--> startup
deactivate triggerOnlinePartitionStateChange
deactivate startup

@enduml